Add SDK constraint check in pubspec.yaml
Added a check for SDK constraint in pubspec.yaml.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -39,7 +39,14 @@ jobs:
 
       - name: Install dependencies
         run: flutter pub get
-
+      
+      - name: Check pubspec.yaml
+        run: |
+          cat pubspec.yaml
+          if ! grep -q "sdk:" pubspec.yaml; then
+          echo "ERROR: pubspec.yaml missing SDK constraint"
+          exit 1
+          fi
       - name: Generate Android Launcher Icons
         run: |
           # Sirf Android ke liye icon generate karein
